site_name: UCLCSSA新生手册
theme:
  name: "material"
  language: "zh"
  icon:
    logo: fontawesome/solid/book-reader
  palette:
    primary: "red"
    accent: "pink"
  features:
    - tabs
    - instant

copyright: "Copyright &copy; 2002 - 2020 UCLCSSA"

nav:
  - 序言: README.md
  - Welcome to UCL: welcome-to-ucl.md
  - 行前准备: hang-qian-zhun-bei.md
  - 初到伦敦: chu-dao-lun-dun.md
  - 校园生活: xiao-yuan-sheng-huo.md
  - 伦敦生活: lun-dun-sheng-huo.md
  - 关于 UCL CSSA: guan-yu-uclcssa.md
  - 特别鸣谢: te-bie-ming-xie-1.md
  - 写在最后: xie-zai-zui-hou.md


markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.tasklist:
      clickable_checkbox: true

extra_css:
  - "stylesheets/style.css"

extra_javascript:
  - "js/baidu.js"

extra:
  social:
    - icon: fontawesome/solid/link
      link: "https://www.uclcssa.org/"
    - icon: fontawesome/brands/facebook
      link: "https://www.facebook.com/691076590989125/"
    - icon: fontawesome/brands/weibo
      link: "https://www.weibo.com/cssaucl/"
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/uclcssa"

google_analytics:
  - "UA-128171628-5"
  - "auto"
